version: '3.3'

networks:
    nginx_parser-php_parser:

services:
    nginx_parser:
        image: nginx:stable-alpine
        container_name: nginx-parser
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - nginx_parser-php_parser
    php_parser:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php-parser
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/project
            - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - nginx_parser-php_parser